// <auto-generated />
using System;
using Funda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Funda.Migrations
{
    [DbContext(typeof(FundaDbContext))]
    partial class FundaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Funda.Data.Entities.Object", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("Adres");

                    b.Property<string>("BronCode");

                    b.Property<string>("Foto");

                    b.Property<bool>("HasTuin");

                    b.Property<double?>("Huurprijs");

                    b.Property<int>("MakelaarId");

                    b.Property<string>("MakelaarNaam");

                    b.Property<string>("MigrationVersion");

                    b.Property<string>("ProjectNaam");

                    b.HasKey("Id");

                    b.ToTable("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
